services:
- type: web
  name: servicediscovery
  env: docker
  buildCommand: docker build -t servicediscovery ./servicediscovery
  startCommand: docker run -p 30000:8761 servicediscovery
- type: web
  name: userservice
  env: docker
  buildCommand: docker build -t userservice ./userservice
  startCommand: docker run -p 30001:30001 -e SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-coai73sf7o1s73dqp5e0-a.singapore-postgres.render.com/kubedb -e SPRING_DATASOURCE_USERNAME=user1 -e SPRING_DATASOURCE_PASSWORD=bPnvbL1MqKFfRM9MbcV7lQxZuDub0Yjp userservice
- type: web
  name: messageservice
  env: docker
  buildCommand: docker build -t messageservice ./messageservice
  startCommand: docker run -p 30002:30002 messageservice
