services:
- type: web
  name: servicediscovery
  env: docker
  buildCommand: docker build -t servicediscovery ./servicediscovery
- type: web
  name: userservice
  env: docker
  buildCommand: docker build -t userservice ./userservice
  envVars:
  - key: SPRING_DATASOURCE_URL
    value: jdbc:postgresql://dpg-coai73sf7o1s73dqp5e0-a.singapore-postgres.render.com/kubedb
  - key: SPRING_DATASOURCE_USERNAME
    value: user1
  - key: SPRING_DATASOURCE_PASSWORD
    value: bPnvbL1MqKFfRM9MbcV7lQxZuDub0Yjp
- type: web
  name: messageservice
  env: docker
  buildCommand: docker build -t messageservice ./messageservice
